version: '3.8'

services:
  egxpilot-init:
    image: node:18-alpine
    container_name: egxpilot-init
    environment:
      - NODE_ENV=development
      - DB_HOST=sqlserver
      - DB_USER=sa
      - DB_PASSWORD=curhi6-qEbfid
      - DB_NAME=egxpilot_dev
      - DB_PORT=1433
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && node scripts/init-database.js"
    networks:
      - sla-api_app-network

networks:
  sla-api_app-network:
    external: true
